[DEFAULT]
PAGE_TITLE = LangGraph: Build stateful Agentic AI graph
LLM_OPTIONS = Groq 
USECASE_OPTIONS = Basic chatbot, Chatbot with Tool, AI News, Blog Generator
GROQ_MODEL_OPTIONS = openai/gpt-oss-120b
#GROQ_API_KEY = 'REDACTED_GROQ_KEY'
